### ISSUE TITLE
Implicitly declaring getopt() in Windows+MinGW build 

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/ssb-dbgen#67]
When we build on Windows+MinGW (with GCC 8.1.0), we get:
```
C:\Users\travis\build\eyalroz\ssb-dbgen\src\driver.c: In function 'process_options':
C:\Users\travis\build\eyalroz\ssb-dbgen\src\driver.c:741:19: warning: implicit declaration of function 'getopt'; did you mean 'getpid'? [-Wimplicit-function-declaration]
  while ((option = getopt (count, vector,
                   ^~~~~~
                   getpid
```
and indeed, nothing in `driver.c` seems to be defining `getopt()` (e.g. we don't include `dss.h` which defines it).
